global using Xunit;
global using System.Xml;
global using GisGmp.Common;
global using GisGmp.Services.ImportСertificates;
global using GisGmp.Income;
global using GisGmp.Package;
global using GisGmp.Refund;
global using GisGmp.Services.SubscriptionService;
global using GisGmp.Subscription;
global using static GisGmp.GisGmpBuilder;
global using static GisGmp.Tests.Tools;